# Generated by Django 3.2 on 2022-08-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LumberData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(blank=True, max_length=25)),
                ('Open', models.FloatField(blank=True, max_length=25)),
                ('High', models.FloatField(blank=True, max_length=25)),
                ('Low', models.FloatField(blank=True, max_length=25)),
                ('Close', models.FloatField(blank=True, max_length=25)),
                ('Volume', models.PositiveIntegerField(blank=True, max_length=25)),
                ('Dividends', models.PositiveIntegerField(blank=True, max_length=25)),
                ('Stock_Splits', models.PositiveIntegerField(blank=True, max_length=25)),
            ],
        ),
    ]
